### ISSUE TITLE
HouseNumber sometimes requires extension

### ISSUE THREAD

**Issue by eelco2k** [nickurt/laravel-postcodeapi#6]
Sometimes it is required to have a correct extension number for a housenumber to return a existing address.

**Comment by nickurt** [comment]
Can you give some more info about this, e.g. which provider-provider you are using?

**Comment by syzygyinteractivemedia** [comment]
i'm using the Pro6PP_NL provider. 

And when i try to do a autocomplete without extension number for example "Kalverstraat 31" at postalcode "1012NX". Then it returns streetnumber without extension is not found. So i need to specify a extension number (and on the 31th there is A, B and C) So i should lookup with autocomplete with "Kalverstraat 31A" where A is the extension number. But that's not possible now.

**Comment by syzygyinteractivemedia** [comment]
I will give you an example:

https://api.pro6pp.nl/v1/autocomplete?auth_key=API_KEY&nl_sixpp=6245BL&streetnumber=26&extension=

you should enter your own api key. but i will post result here:

https://api.pro6pp.nl/v1/autocomplete?auth_key=API_KEY&nl_sixpp=6245BL&streetnumber=26
result:
{
status: "ok",
results: [
{
nl_sixpp: "6245BL",
street: "Diepstraat",
city: "Eijsden",
municipality: "Eijsden-Margraten",
province: "Limburg",
streetnumbers: "2-24;28-38;42-48;12 A;14 A;26 A;26 B;26 C;26 D;26 E;26 F;26 G;26 H;6 A",
lat: 50.77576,
lng: 5.70212,
areacode: "043"
}
]
}

https://api.pro6pp.nl/v1/autocomplete?auth_key=API_KEY&nl_sixpp=6245BL&streetnumber=26&extension=
result:

{
status: "error",
error: {
message: "Streetnumber without extension not found"
},
results: [ ]
}

And because the library always sends &extension= (an empty string) it always returns an error.

**Comment by nickurt** [comment]
The [Pro6PP_NL](https://github.com/nickurt/laravel-postcodeapi/blob/master/src/Providers/nl_NL/Pro6PP_NL.php)-provider only supports the function 'find' (ByPostcode) for now, the function 'findByPostcodeAndHouseNumber' is not supported at this moment.
