### ISSUE TITLE
Caching responses

### ISSUE THREAD

**Issue by niladam** [nickurt/laravel-postcodeapi#7]
Hello,

Do you think it could be possible to have the responses cached for a specific period of time ? Maybe in a separate table or something, and have the API first check if the postcode is already cached and return the CACHED responses ? 

This could save a few roundtrips to any API provider and also could limit the number of the API requests -- therefore reducing costs.

**Comment by nickurt** [comment]
This feature is currently not on my roadmap, because I don't think this should be included in this package. There are some very good packages for Laravel about cache/redis/etc to make this already working.

But, if you really want this feature to be included, feel free to create a pull-request for this.

**Comment by niladam** [comment]
@nickurt i think i will. I'm using this and i just wanted a quick and dirty caching. I have already tested it and it works -- however, i'm due for a really long meeting presenting a project and i won't be able to tackle this until until after maybe 9 - 10 September.

**Comment by nickurt** [comment]
Ok, no problem, take your time.

**Comment by nickurt** [comment]
@niladam any update on this?

**Comment by niladam** [comment]
Oh crap. I totally forgot this. I'll have to postpone again..
